# Stubs for blinkpy.helpers.util module
from pathlib import Path
from typing import Any

def load_saved_blink(file_path: str | Path) -> Any | None: ...
def cleanup_blink_session(blink: Any) -> None: ...
def get_time() -> int: ...
def time_to_utc(timestamp: int | str) -> int: ...
def local_storage_clip_path_template() -> str: ...
def merge_dicts(dict1: dict[str, Any], dict2: dict[str, Any]) -> dict[str, Any]: ...
def json_load(file_path: str | Path) -> dict[str, Any]: ...
