# Stubs for blinkpy.helpers.util module
from collections.abc import Callable
from pathlib import Path
from typing import Any, TypeVar

F = TypeVar("F", bound=Callable[..., Any])

# Async functions
async def json_load(file_name: str | Path) -> dict[str, Any] | None: ...
async def json_save(data: dict[str, Any], file_name: str | Path) -> None: ...

# Sync utility functions
def json_dumps(json_in: dict[str, Any], indent: int = 2) -> str: ...
def gen_uid(size: int, uid_format: bool = False) -> str: ...
def get_time(time_to_convert: str | int | None = None) -> int: ...
def time_to_seconds(timestamp: str | int) -> int: ...
def backoff_seconds(retry: int = 0, default_time: int = 1) -> int: ...
def to_alphanumeric(name: str) -> str: ...
def local_storage_clip_url_template() -> str: ...
def merge_dicts(dict_a: dict[str, Any], dict_b: dict[str, Any]) -> dict[str, Any]: ...
def prompt_login_data(data: dict[str, Any]) -> dict[str, Any]: ...
def validate_login_data(data: dict[str, Any]) -> bool: ...

# Exception classes
class BlinkException(Exception):
    errid: str
    message: str
    def __init__(self, errcode: tuple[str, str]) -> None: ...

class BlinkAuthenticationException(BlinkException): ...

# URL handler class
class BlinkURLHandler:
    subdomain: str
    base_url: str
    home_url: str
    event_url: str
    network_url: str
    networks_url: str
    video_url: str
    def __init__(self, region_id: str) -> None: ...

# Throttle decorator class
class Throttle:
    throttle_time: int
    last_call: int
    def __init__(self, seconds: int = 10) -> None: ...
    def __call__(self, method: F) -> F: ...

# Legacy functions for compatibility
def load_saved_blink(file_path: str | Path) -> Any | None: ...
def cleanup_blink_session(blink: Any) -> None: ...
