# Stubs for blinkpy.helpers.util module
from collections.abc import Callable
from pathlib import Path
from typing import Any, TypeVar

F = TypeVar("F", bound=Callable[..., Any])

# Async functions
async def json_load(file_name: str | Path) -> dict[str, Any] | None: ...
async def json_save(data: dict[str, Any], file_name: str | Path) -> None: ...

# Sync utility functions
def json_dumps(json_in: dict[str, Any], indent: int = 2) -> str: ...
def gen_uid(size: int, uid_format: bool = False) -> str: ...
def get_time() -> int: ...
def time_to_seconds(timestamp: str | int) -> int: ...
def backoff_seconds(attempt: int, max_backoff: int = 300) -> int: ...
def to_alphanumeric(name: str) -> str: ...
def local_storage_clip_url_template() -> str: ...
def merge_dicts(dict1: dict[str, Any], dict2: dict[str, Any]) -> dict[str, Any]: ...

# Decorators
def Throttle(seconds: int) -> Callable[[F], F]: ...

# Legacy functions for compatibility
def load_saved_blink(file_path: str | Path) -> Any | None: ...
def cleanup_blink_session(blink: Any) -> None: ...
