# Stubs for blinkpy.camera module
from typing import Any

class BlinkCamera:
    """Camera class for individual Blink cameras."""

    blink: Any
    sync: Any
    name: str
    camera_id: str  # Change from int to str based on usage

    def __init__(self, sync: Any) -> None: ...
    async def async_arm(self, value: bool) -> bool: ...
    async def snap_picture(self) -> bool: ...
    async def get_sensor_info(self) -> dict[str, Any]: ...
    async def get_liveview(self) -> dict[str, Any]: ...
    async def init_livestream(self) -> str | None: ...
    def get_videos_metadata(
        self,
        since: int | None = None,
        stop: int = 10,
    ) -> dict[str, Any]: ...
    async def refresh(self) -> None: ...

    # Properties commonly used in your code
    @property
    def arm(self) -> bool: ...
    @property
    def motion_enabled(self) -> bool: ...
    @property
    def battery(self) -> str | None: ...
    @property
    def battery_voltage(self) -> float | None: ...
    @property
    def temperature(self) -> float | None: ...
    @property
    def temperature_c(self) -> float | None: ...
    @property
    def wifi_strength(self) -> int: ...
    @property
    def thumbnail(self) -> str | None: ...
    @property
    def clip(self) -> str | None: ...
    @property
    def video_from_cache(self) -> bytes | None: ...
    @property
    def image_from_cache(self) -> bytes | None: ...
    @property
    def last_record(self) -> str | int | None: ...  # Fix type based on usage
    @property
    def recent_clips(self) -> list[dict[str, Any]]: ...
    @property
    def status(self) -> str: ...
    @property
    def serial(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def night_vision(self) -> str: ...
    @property
    def attributes(self) -> dict[str, Any]: ...
    @property
    def online(self) -> bool: ...
