# Stubs for blinkpy.livestream module
from typing import Any

class BlinkLiveStream:
    """Class to initialize individual stream."""

    def __init__(self, camera: Any, response: dict[str, Any]) -> None: ...
    async def start(self) -> None: ...
    async def feed(self) -> None: ...
    def stop(self) -> None: ...
    @property
    def url(self) -> str: ...
