# Stubs for blinkpy.camera module
import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

from aiohttp import ClientResponse

if TYPE_CHECKING:
    from .livestream import BlinkLiveStream
    from .sync_module import BlinkSyncModule

class BlinkCamera:
    """Camera class for individual Blink cameras."""

    # Core attributes from __init__
    sync: BlinkSyncModule
    name: str | None
    camera_id: str | None
    network_id: str | None
    thumbnail: str | None
    serial: str | None
    motion_enabled: bool | None
    battery_level: int | None
    clip: str | None
    recent_clips: list[dict[str, Any]]
    temperature: float | None
    temperature_calibrated: float | None
    battery_state: str | None
    motion_detected: bool | None
    wifi_strength: int | None
    last_record: dict[str, Any] | None
    camera_type: str
    product_type: str | None
    sync_signal_strength: int | None

    # Private attributes
    _version: str | None
    _battery_voltage: float | None
    _cached_image: bytes | None
    _cached_video: bytes | None

    def __init__(self, sync: BlinkSyncModule) -> None: ...

    # Properties
    @property
    def attributes(self) -> dict[str, Any]: ...
    @property
    def battery(self) -> str: ...
    @property
    def battery_voltage(self) -> float | None: ...
    @property
    def temperature_c(self) -> float | None: ...
    @property
    def image_from_cache(self) -> bytes | None: ...
    @property
    def video_from_cache(self) -> bytes | None: ...
    @property
    def version(self) -> str | None: ...
    @property
    def arm(self) -> bool: ...

    # Async methods
    async def async_arm(self, value: bool) -> bool: ...
    async def night_vision(self) -> dict[str, str | int | None] | None: ...
    async def async_set_night_vision(self, value: str) -> bool: ...
    async def record(self) -> bool: ...
    async def get_media(self, media_type: str = "image") -> ClientResponse | None: ...
    async def get_thumbnail(self, url: str | None = None) -> ClientResponse | None: ...
    async def get_video_clip(self, url: str | None = None) -> ClientResponse | None: ...
    async def snap_picture(self) -> bool: ...
    async def set_motion_detect(self, enable: bool) -> bool: ...
    async def update(
        self,
        config: dict[str, Any],
        force_cache: bool = False,
        expire_clips: bool = True,
        **kwargs: Any,
    ) -> None: ...
    async def get_sensor_info(self) -> dict[str, Any]: ...
    async def update_images(
        self,
        config: dict[str, Any],
        force_cache: bool = False,
        expire_clips: bool = True,
    ) -> None: ...
    async def expire_recent_clips(self, delta: datetime.timedelta = ...) -> None: ...
    async def get_liveview(self) -> str: ...
    async def init_livestream(
        self,
    ) -> BlinkLiveStream: ...  # Can raise NotImplementedError
    async def image_to_file(self, path: str | Path) -> None: ...
    async def video_to_file(self, path: str | Path) -> None: ...
    async def save_recent_clips(
        self,
        path: str | Path,
        since: int | None = None,
        stop: int = 10,
        delay: int = 1,
        debug: bool = False,
    ) -> None: ...

    # Sync methods
    def extract_config_info(self, config: dict[str, Any]) -> None: ...

class BlinkCameraMini(BlinkCamera):
    """Blink Mini camera."""

    def __init__(self, sync: BlinkSyncModule) -> None: ...
    @property
    def arm(self) -> bool: ...
    async def async_arm(self, value: bool) -> bool: ...
    async def record(self) -> bool: ...
    async def snap_picture(self) -> bool: ...
    async def get_sensor_info(self) -> dict[str, Any]: ...
    async def get_liveview(self) -> str: ...
    async def init_livestream(
        self,
    ) -> BlinkLiveStream: ...  # Can raise NotImplementedError

class BlinkDoorbell(BlinkCamera):
    """Blink Doorbell camera."""

    def __init__(self, sync: BlinkSyncModule) -> None: ...
    @property
    def arm(self) -> bool: ...
    async def async_arm(self, value: bool) -> bool: ...
    async def record(self) -> bool: ...
    async def snap_picture(self) -> bool: ...
    async def get_sensor_info(self) -> dict[str, Any]: ...
    async def get_liveview(self) -> str: ...
    async def init_livestream(
        self,
    ) -> BlinkLiveStream: ...  # Can raise NotImplementedError
