# Stubs for blinkpy.sync_module module
import datetime
from typing import TYPE_CHECKING, Any

from aiohttp import ClientResponse
from requests.structures import CaseInsensitiveDict

from .camera import BlinkCamera

if TYPE_CHECKING:
    from .blinkpy import Blink

class BlinkSyncModule:
    """Sync module class for Blink systems."""

    # Core attributes from __init__
    blink: Blink  # Blink instance
    response: dict[str, Any]
    cameras: CaseInsensitiveDict[BlinkCamera]
    _local_storage: dict[str, Any]
    sync_id: int | None
    region_id: str | None
    events: list[dict[str, Any]]
    motion_interval: int
    motion: dict[str, Any]
    last_records: dict[str, list[dict[str, Any]]]
    network_info: dict[str, Any] | None
    summary: dict[str, Any] | None
    _version: str | None

    def __init__(
        self,
        blink: Blink,
        network_name: str,
        network_id: int,
        camera_list: dict[str, Any],
    ) -> None: ...

    # Async methods
    async def start(self) -> None: ...
    async def async_arm(
        self, value: bool
    ) -> dict[str, Any] | ClientResponse | None: ...
    async def sync_initialize(self) -> None: ...
    async def _init_local_storage(self, sync_id: str) -> None: ...
    async def update_cameras(self, camera_type: type[BlinkCamera] = ...) -> None: ...
    async def get_events(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_camera_info(
        self, camera_id: str, **kwargs: Any
    ) -> dict[str, Any]: ...
    async def get_network_info(self) -> dict[str, Any]: ...
    async def refresh(self, force_cache: bool = False) -> bool: ...
    async def check_new_videos(self) -> None: ...
    async def get_owl_info(self) -> dict[str, Any]: ...
    async def update_local_storage_manifest(self) -> bool: ...
    async def prepare_download(self, item_id: int) -> bool: ...
    async def download_video(self, item_id: int, filename: str) -> bool: ...

    # Sync methods
    def get_unique_info(self, name: str) -> dict[str, Any]: ...
    def check_new_video_time(
        self, timestamp: int, reference: int | None = None
    ) -> bool: ...
    def get_videos_metadata(
        self,
        since: int | None = None,
        stop: int = 10,
    ) -> dict[str, Any]: ...

    # Properties
    @property
    def attributes(self) -> dict[str, Any]: ...
    @property
    def urls(self) -> dict[str, str]: ...
    @property
    def version(self) -> str: ...
    @property
    def arm(self) -> bool: ...
    @property
    def online(self) -> bool: ...
    @property
    def wifi_strength(self) -> int: ...
    @property
    def temperature(self) -> float | None: ...
    @property
    def battery(self) -> str | None: ...
    @property
    def local_storage(self) -> bool: ...
    @property
    def local_storage_manifest_ready(self) -> bool: ...
    @property
    def network_id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def status(self) -> str: ...
    @property
    def serial(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def last_record(self) -> dict[str, Any]: ...

class BlinkOwl(BlinkSyncModule):
    """Blink Owl (Mini) sync module class."""

class BlinkLotus(BlinkSyncModule):
    """Blink Lotus sync module class."""

class LocalStorageMediaItem:
    """Metadata of media item in the local storage manifest."""

    # Private attributes
    _id: int
    _camera_name: str
    _created_at: datetime.datetime
    _size: int
    _url_template: str
    _manifest_id: str

    def __init__(
        self,
        item_id: str | int,
        camera_name: str,
        created_at: str,
        size: int,
        manifest_id: str,
        url_template: str,
    ) -> None: ...

    # Properties
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def created_at(self) -> datetime.datetime: ...
    @property
    def size(self) -> int: ...
    @property
    def url(self, manifest_id: str | None = None) -> str: ...

    # Methods
    def _build_url(self, manifest_id: str, clip_id: str) -> str: ...
    async def prepare_download(self, blink: Blink, max_retries: int = 4) -> bool: ...
    async def delete_video(self, blink: Blink, max_retries: int = 4) -> bool: ...
    async def download_video(
        self, blink: Blink, file_name: str, max_retries: int = 4
    ) -> bool: ...
    async def download_video_delete(
        self, blink: Blink, file_name: str, max_retries: int = 4
    ) -> bool: ...

    # Magic methods
    def cmp_key(self) -> datetime.datetime: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: LocalStorageMediaItem) -> bool: ...
    def __hash__(self) -> int: ...
